### ISSUE TITLE
link.py error

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/datman#6]
putting this here to remind myself it exists...

    Tue Apr 21 16:08:39 EDT 2015: Link scans...
    ERROR: /archive/data-2.0/COGBDO/data/zips/2014_0604_CM015.zip: 27B022 (header PatientName) not valid scan ID
    ERROR: /archive/data-2.0/COGBDO/data/zips/2014_0604_CM015.zip: Cannot find scan id. Skipping
    Traceback (most recent call last):
      File "/archive/data-2.0/code/datman/bin/link.py", line 212, in <module>
        main()
      File "/archive/data-2.0/code/datman/bin/link.py", line 115, in main
        stop_after_first=True).values()[0]
    IndexError: list index out of range

**Comment by josephdviviano** [comment]
I'm closing this. We can reopen if the bug pops up again.
